
# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE		= attiny45
CLOCK		= 8000000
PROGRAMMER 	= -c usbasp
OBJECTS		= *.cpp
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES	= -U lfuse:w:0x62:m -U hfuse:w:0xcf:m -U efuse:w:0xff:m

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-g++ -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE) -std=gnu++11 -Xlinker -Map=build/main.map

# symbolic targets:
all:	main.hex

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash:
	$(AVRDUDE) -U flash:w:build/main.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID main.hex

clean:
	rm -f main.hex main.elf $(OBJECTS)

# file targets:
main.elf: $(OBJECTS)
	rm -rf build
	mkdir build
	$(COMPILE) -o build/main.elf $(OBJECTS)

main.hex: main.elf
	rm -f build/main.hex
	avr-objcopy -j .text -j .data -O ihex build/main.elf build/main.hex
	avr-size --format=avr --mcu=$(DEVICE) build/main.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	main.elf
	avr-objdump -d build/main.elf
